---

#------------------------------------------------------------------------------
# YAML Aliases to simplify maintenance

anchorLinks:
  - flowAnimation: &flow-slow
      thresholdOffValue: 2
      thresholdLwrValue: 10
      thresholdLwrDurationSecs: 1
      thresholdUprValue: 100
      thresholdUprDurationSecs: 0.1

#------------------------------------------------------------------------------
# Panel Config

cellIdPreamble: "cell-"
gradientMode: "hue"
cells:
  dex:
    dataRef: "A-series test"
    label:
      separator: "cr"
      units: "percent"
      decimalPoints: 0
    labelColor:
      thresholdsRef: "percentage"
    linkRef: "google"
  dex_rate:
    dataRef: "test-data-small-cos"
    label:
      separator: "colon"
      units: "ms"
      decimalPoints: 0
  dex_transactions:
    dataRef: 'test-data-small-cos'
    flowAnimation: *flow-slow
  docs:
    linkRef: "grafana-flow-docs"
  light_processor:
    dataRef: 'test-data-light_processor'
    label:
      units: 'ms'
      decimalPoints: 0
  light_processor_rate:
    dataRef: 'test-data-light_processor_rate'
    label:
      units: 'ms'
      decimalPoints: 0
  node:
    dataRef: 'test-data-node'
    label:
      units: 'ms'
      decimalPoints: 0
  node_rate:
    dataRef: 'test-data-node_rate'
    label:
      units: 'ms'
      decimalPoints: 0
  on_chain:
    dataRef: 'test-data-on_chain'
    label:
      units: 'ms'
      decimalPoints: 0
  sa:
    dataRef: "A-series2 test"
    label:
      separator: "cr"
      units: "percent"
      decimalPoints: 0
    labelColor:
      thresholdsRef: "percentage"
  sa_rate:
    dataRef: "test-data-small-sin"
    label:
      separator: "colon"
      units: "ms"
      decimalPoints: 0
  sa_transactions:
    dataRef: 'test-data-small-sin'
    flowAnimation: *flow-slow
  vault:
    dataRef: 'test-data-vault'
    label:
      units: 'ms'
      decimalPoints: 0
  vault_rate:
    dataRef: 'test-data-vault_rate'
    label:
      units: 'ms'
      decimalPoints: 0
  wallet:
    dataRef: 'test-data-wallet'
    label:
      units: 'ms'
      decimalPoints: 0
  wallet_rate:
    dataRef: "B-test"
    label:
      separator: "colon"
      units: "ms"
      decimalPoints: 0
  web:
    dataRef: "A-series1 test"    # simulate high traffic volume
    label:
      separator: "cr"
      units: "percent"
      decimalPoints: 0
    labelColor:
      thresholdsRef: "percentage"
  web_rate:
    dataRef: "test-data-small-cos"
    label:
      separator: "colon"
      units: "ms"
      decimalPoints: 0
  web_transactions:
    dataRef: "test-data-small-cos"
    flowAnimation: *flow-slow
