---

#------------------------------------------------------------------------------
# YAML Aliases to simplify maintenance

anchorLinks:
  - flowAnimation: &flow-slow
      thresholdOffValue: 2
      thresholdLwrValue: 10
      thresholdLwrDurationSecs: 1
      thresholdUprValue: 100
      thresholdUprDurationSecs: 0.1
  - link: &google
      url: "https://google.com/"
      params: "time"

#------------------------------------------------------------------------------
# Panel Config

cellIdPreamble: "cell-"
gradientMode: "hue"
cells: 
  web:
    dataRef: "test-data-large-sin"
    label:
      separator: "cr"
      units: ""
      decimalPoints: 0
    labelColor:
      gradientMode: "hue"
      thresholds:
        - {color: "green", level: 0}
        - {color: "orange", level: 500}
        - {color: "red", level: 1000}
  web_rate:
    dataRef: "test-data-small-cos"
    label:
      separator: "colon"
      units: "ms"
      decimalPoints: 0
  web_transactions:
    dataRef: "test-data-small-cos"
    flowAnimation: *flow-slow
  dex:
    dataRef: "A-series"
    label:
      separator: "cr"
      units: ""
    labelColor:
      thresholds:
        - {color: "green", level: 0}
        - {color: "red", level: 100}
    link: *google
  dex_rate:
    dataRef: "test-data-small-sin"
    label:
      separator: "cr"
      units: "ms"
      decimalPoints: 0
  sa:
    dataRef: "test-data-small-cos"
    label:
      separator: "cr"
      units: ""
      decimalPoints: 0
  sa_rate:
    dataRef: "test-data-small-sin"
    label:
      separator: "colon"
      units: "ms"
      decimalPoints: 0
